package com.gildedgames.aether.event.listener;

import com.gildedgames.aether.client.render.entity.RenderAechorPlant;
import com.gildedgames.aether.client.render.entity.RenderAerbunny;
import com.gildedgames.aether.client.render.entity.RenderAerwhale;
import com.gildedgames.aether.client.render.entity.RenderCloudParachute;
import com.gildedgames.aether.client.render.entity.RenderCockatrice;
import com.gildedgames.aether.client.render.entity.RenderDartEnchanted;
import com.gildedgames.aether.client.render.entity.RenderDartGolden;
import com.gildedgames.aether.client.render.entity.RenderDartPoison;
import com.gildedgames.aether.client.render.entity.RenderFiroBall;
import com.gildedgames.aether.client.render.entity.RenderFlamingArrow;
import com.gildedgames.aether.client.render.entity.RenderFloatingBlock;
import com.gildedgames.aether.client.render.entity.RenderFlyingCow;
import com.gildedgames.aether.client.render.entity.RenderHomeShot;
import com.gildedgames.aether.client.render.entity.RenderMimic;
import com.gildedgames.aether.client.render.entity.RenderMoa;
import com.gildedgames.aether.client.render.entity.RenderPhyg;
import com.gildedgames.aether.client.render.entity.RenderPoisonNeedle;
import com.gildedgames.aether.client.render.entity.RenderSheepuff;

import static com.gildedgames.aether.Aether.MODID;
import static net.modificationstation.stationapi.api.registry.Identifier.of;
import com.gildedgames.aether.client.render.entity.RenderSlider;
import com.gildedgames.aether.client.render.entity.RenderSwet;
import com.gildedgames.aether.client.render.entity.RenderValkyrie;
import com.gildedgames.aether.client.render.entity.RenderWhirly;
import com.gildedgames.aether.client.render.entity.RenderZephyr;
import com.gildedgames.aether.client.render.entity.RenderZephyrSnowball;
import com.gildedgames.aether.client.render.model.ModelAechorPlant;
import com.gildedgames.aether.client.render.model.ModelAerbunny;
import com.gildedgames.aether.client.render.model.ModelCockatrice;
import com.gildedgames.aether.client.render.model.ModelFireMinion;
import com.gildedgames.aether.client.render.model.ModelFireMonster;
import com.gildedgames.aether.client.render.model.ModelFlyingCow1;
import com.gildedgames.aether.client.render.model.ModelFlyingCow2;
import com.gildedgames.aether.client.render.model.ModelFlyingPig1;
import com.gildedgames.aether.client.render.model.ModelFlyingPig2;
import com.gildedgames.aether.client.render.model.ModelHomeShot;
import com.gildedgames.aether.client.render.model.ModelMiniCloud;
import com.gildedgames.aether.client.render.model.ModelMoa;
import com.gildedgames.aether.client.render.model.ModelSheepuff1;
import com.gildedgames.aether.client.render.model.ModelSheepuff2;
import com.gildedgames.aether.client.render.model.ModelSheepuff3;
import com.gildedgames.aether.client.render.model.ModelSlider;
import com.gildedgames.aether.client.render.model.ModelValkyrie;
import com.gildedgames.aether.entity.EntityCloudParachute;
import com.gildedgames.aether.entity.animal.EntityAechorPlant;
import com.gildedgames.aether.entity.animal.EntityAerbunny;
import com.gildedgames.aether.entity.animal.EntityFlyingCow;
import com.gildedgames.aether.entity.animal.EntityMoa;
import com.gildedgames.aether.entity.animal.EntityPhyg;
import com.gildedgames.aether.entity.animal.EntitySheepuff;
import com.gildedgames.aether.entity.animal.EntitySwet;
import com.gildedgames.aether.entity.animal.Whirly;
import com.gildedgames.aether.entity.boss.EntityFireMonster;
import com.gildedgames.aether.entity.boss.EntitySlider;
import com.gildedgames.aether.entity.boss.EntityValkyrie;
import com.gildedgames.aether.entity.mobs.EntityAerwhale;
import com.gildedgames.aether.entity.mobs.EntityCockatrice;
import com.gildedgames.aether.entity.mobs.EntityFireMinion;
import com.gildedgames.aether.entity.mobs.EntityHomeShot;
import com.gildedgames.aether.entity.mobs.EntityMimic;
import com.gildedgames.aether.entity.mobs.EntityMiniCloud;
import com.gildedgames.aether.entity.mobs.EntityZephyr;
import com.gildedgames.aether.entity.projectile.EntityDartEnchanted;
import com.gildedgames.aether.entity.projectile.EntityDartGolden;
import com.gildedgames.aether.entity.projectile.EntityDartPoison;
import com.gildedgames.aether.entity.projectile.EntityFiroBall;
import com.gildedgames.aether.entity.projectile.EntityFlamingArrow;
import com.gildedgames.aether.entity.projectile.EntityFloatingBlock;
import com.gildedgames.aether.entity.projectile.EntityPoisonNeedle;
import com.gildedgames.aether.entity.projectile.EntityZephyrSnowball;
import com.gildedgames.aether.mixin.MinecraftClientAccessor;

import io.github.prospector.modmenu.mixin.MinecraftAccessor;
import net.mine_diver.unsafeevents.listener.EventListener;
import net.minecraft.client.render.entity.BipedEntityRenderer;
import net.minecraft.client.render.entity.LivingEntityRenderer;
import net.minecraft.client.render.entity.model.Slime;
import net.modificationstation.stationapi.api.client.event.render.entity.EntityRendererRegisterEvent;
import net.modificationstation.stationapi.api.event.registry.MobHandlerRegistryEvent;
public class EntityRendererListener {
    @EventListener
    private static void registerEntity(EntityRendererRegisterEvent event) {
        event.renderers.put(EntityFlyingCow.class, new RenderFlyingCow(new ModelFlyingCow1(), new ModelFlyingCow2(), 0.7f));
        event.renderers.put(EntityZephyr.class, new RenderZephyr());
        event.renderers.put(EntityZephyrSnowball.class, new RenderZephyrSnowball());
        event.renderers.put(EntitySlider.class, new RenderSlider(new ModelSlider(0.0f, 12.0f), 1.5f));
        event.renderers.put(EntityValkyrie.class, new RenderValkyrie(new ModelValkyrie(), 0.3f));
        event.renderers.put(EntityPoisonNeedle.class, new RenderPoisonNeedle());
        event.renderers.put(EntityDartPoison.class, new RenderDartPoison());
        event.renderers.put(EntityDartGolden.class, new RenderDartGolden());
        event.renderers.put(EntityDartEnchanted.class, new RenderDartEnchanted());
        event.renderers.put(EntityFireMonster.class, new BipedEntityRenderer(new ModelFireMonster(0.0f, 0.0f), 0.4f));
        event.renderers.put(EntityFireMinion.class, new BipedEntityRenderer(new ModelFireMinion(0.0f, 0.0f), 0.4f));
        event.renderers.put(EntityFiroBall.class, new RenderFiroBall(new ModelHomeShot(0.5f, 0.0f), 0.25f));
        event.renderers.put(EntityFloatingBlock.class, new RenderFloatingBlock());
        event.renderers.put(EntityMimic.class, new RenderMimic());
        event.renderers.put(EntityMoa.class, new RenderMoa(new ModelMoa(), 1.0f));
        event.renderers.put(EntityAerwhale.class, new RenderAerwhale());
        event.renderers.put(EntityCockatrice.class, new RenderCockatrice(new ModelCockatrice(), 1.0f));
        event.renderers.put(EntitySheepuff.class, new RenderSheepuff(new ModelSheepuff1(), new ModelSheepuff2(), new ModelSheepuff3(), 0.7f));
        event.renderers.put(EntityPhyg.class, new RenderPhyg(new ModelFlyingPig1(), new ModelFlyingPig2(), 0.7f));
        event.renderers.put(EntitySwet.class, new RenderSwet(new Slime(16), new Slime(0), 0.3f));
        event.renderers.put(EntityAechorPlant.class, new RenderAechorPlant(new ModelAechorPlant(), 0.3f));
        event.renderers.put(EntityAerbunny.class, new RenderAerbunny(new ModelAerbunny(), 0.3f));
        event.renderers.put(EntityCloudParachute.class, new RenderCloudParachute());
        event.renderers.put(EntityFlamingArrow.class, new RenderFlamingArrow());
        event.renderers.put(EntityHomeShot.class, new RenderHomeShot(new ModelHomeShot(0.0f, 0.0f), 0.2f));
        //event.renderers.put(EntityNotchWave.class, new RenderNotchWave());
        //event.renderers.put(EntityAetherLightning.class, new LightningRenderer());
        //event.renderers.put(EntityLightningKnife.class, new RenderLightningKnife());
        //map.put(EntitySentry.class, new RenderSentry(new Slime(0), 0.2f));
        event.renderers.put(EntityMiniCloud.class, new LivingEntityRenderer(new ModelMiniCloud(0.0f, 20.0f), 0.35f));
        event.renderers.put(Whirly.class, new RenderWhirly());
    }
}